doctrine:
    dbal:
        driver: 'pdo_pgsql'
        dbname: '%env(DB_NAME)%'
        host: '%env(DB_HOST)%'
        options:
            search_path: public
        #port: ~
        user: '%env(DB_USER)%'
        password: '%env(DB_PASSWORD)%'
        charset: "UTF8"
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
